[package]
name = "hurlfmt"
version = "3.0.0"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "format Hurl files"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"

[features]
# Treat warnings as a build error.
strict = []

[dependencies]
atty = "0.2.14"
base64 = "0.21.0"
clap = { version = "4.2.7", features = ["cargo", "wrap_help"] }
colored = "2.0.0"
hurl_core = { version = "3.0.0", path = "../hurl_core" }
regex = "1.8.1"

[dev-dependencies]
proptest = "1.1.0"



