[package]
name = "hurlfmt"
version = "1.7.0-snapshot"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "format Hurl files"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"

[features]
# Treat warnings as a build error.
strict = []

[dependencies]
atty = "0.2.14"
base64 = "0.13.0"
clap = { version = "3.2.16", features = ["cargo"] }
colored = "2.0.0"
hurl_core = { version = "1.7.0-snapshot", path = "../hurl_core" }
regex = "1.6.0"

[dev-dependencies]
proptest = "1.0.0"



