[package]
name = "hurlfmt"
version = "8.0.0-SNAPSHOT"
authors = ["Fabrice Reix <fabrice.reix@orange.com>", "Jean-Christophe Amiel <jeanchristophe.amiel@orange.com>", "Filipe Pinto <filipe.pinto@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Format Hurl files"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"
rust-version = "1.93.1"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.59", features = ["cargo", "wrap_help"] }
hurl_core = { version = "8.0.0-SNAPSHOT", path = "../hurl_core" }
regex = "1.12.3"


[lints]
workspace = true
