[package]
name = "hurlfmt"
version = "5.0.1"
authors = ["Fabrice Reix <fabrice.reix@orange.com>", "Jean-Christophe Amiel <jeanchristophe.amiel@orange.com>", "Filipe Pinto <filipe.pinto@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Format Hurl files"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"
rust-version = "1.78.0"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.17", features = ["cargo", "wrap_help"] }
hurl_core = { version = "5.0.1", path = "../hurl_core" }
regex = "1.10.6"

[dev-dependencies]
proptest = "1.5.0"

[lints]
workspace = true

# cargo-binstall metadata
# See https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md
# for docs explaining the fields here.
[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ version }/hurl-{ version }-{ target }{ archive-suffix }"
bin-dir = "hurl-{ version }-{ target }/bin/{ bin }{ binary-ext }"
