[package]
name = "hurlfmt"
version = "4.2.0-SNAPSHOT"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "format Hurl files"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"

[dependencies]
base64 = "0.21.4"
clap = { version = "4.4.6", features = ["cargo", "wrap_help"] }
colored = "2.0.4"
hurl_core = { version = "4.2.0-SNAPSHOT", path = "../hurl_core" }
regex = "1.9.5"

[dev-dependencies]
proptest = "1.2.0"



