[package]
name = "hurl_core"
version = "1.7.0-snapshot"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Hurl Core"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"

[features]
# Treat warnings as a build error.
strict = []


[dependencies]
float-cmp = "0.9.0"
sxd-document = "0.3.2"
regex = "1.6.0"
