[package]
name = "hurl_core"
version = "4.2.0-SNAPSHOT"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Hurl Core"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"

[dependencies]
float-cmp = "0.9.0"
libxml = "0.3.3"
regex = "1.9.5"
