[package]
name = "hurl_core"
version = "6.1.0-SNAPSHOT"
authors = ["Fabrice Reix <fabrice.reix@orange.com>", "Jean-Christophe Amiel <jeanchristophe.amiel@orange.com>", "Filipe Pinto <filipe.pinto@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Hurl Core"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"

[dependencies]
colored = "3.0.0"
libxml = "0.3.3"
regex = "1.11.1"

[lints]
workspace = true
