[package]
name = "hurl"
version = "7.1.0-SNAPSHOT"
authors = ["Fabrice Reix <fabrice.reix@orange.com>", "Jean-Christophe Amiel <jeanchristophe.amiel@orange.com>", "Filipe Pinto <filipe.pinto@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Hurl, run and test HTTP requests"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"
rust-version = "1.88.0"

[lib]
name = "hurl"

[features]
# Re-export of curl/static-ssl: use a bundled OpenSSL version and statically link to it. Only applies on platforms that
# use OpenSSL
static-openssl = ["curl/static-ssl", "curl-sys/static-ssl"]

[dependencies]
base64 = "0.22.1"
brotli = "8.0.1"
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }
clap = { version = "4.5.42", features = ["string", "wrap_help"] }
curl = "0.4.48"
curl-sys = "0.4.82"
encoding = "0.2.33"
glob = "0.3.2"
hurl_core = { version = "7.1.0-SNAPSHOT", path = "../hurl_core" }
libflate = "2.1.0"
libxml = "0.3.6"
md5 = "0.7.0"
percent-encoding = "2.3.1"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.142", features = ["arbitrary_precision"] }
sha2 = "0.10.9"
url = "2.5.4"
xml-rs = { version = "0.8.27" }
# uuid features: lets you generate random UUIDs and use a faster (but still sufficiently random) RNG
uuid = { version = "1.17.0", features = ["v4" , "fast-rng"] }
similar = "2.7.0"
terminal_size = "0.4.2"

[target.'cfg(unix)'.dependencies]
termion = "4.0.5"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[build-dependencies]
cc = "1.2.31"

[lints]
workspace = true
