[package]
name = "hurl"
version = "4.3.0-SNAPSHOT"
authors = ["Fabrice Reix <fabrice.reix@orange.com>", "Jean-Christophe Amiel <jeanchristophe.amiel@orange.com>", "Filipe Pinto <filipe.pinto@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Hurl, run and test HTTP requests"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"
rust-version = "1.77.1"

[lib]
name = "hurl"

[features]
vendored-openssl = ["curl/static-ssl", "curl-sys/static-ssl"]

[dependencies]
base64 = "0.22.0"
brotli = "5.0.0"
chrono = { version = "0.4.37", default-features = false, features = ["clock"] }
clap = { version = "4.5.4", features = ["cargo", "string", "wrap_help"] }
colored = "2.1.0"
curl = "0.4.46"
curl-sys = "0.4.72"
encoding = "0.2.33"
float-cmp = "0.9.0"
glob = "0.3.1"
hex = "0.4.3"
hex-literal = "0.4.1"
hurl_core = { version = "4.3.0-SNAPSHOT", path = "../hurl_core" }
libflate = "2.0.0"
libxml = "0.3.3"
md5 = "0.7.0"
percent-encoding = "2.3.1"
regex = "1.10.4"
serde = "1.0.197"
serde_json = { version = "1.0.115", features = ["arbitrary_precision"] }
sha2 = "0.10.8"
url = "2.5.0"
xml-rs = { version = "0.8.20" }
lazy_static = "1.4.0"
# uuid features: lets you generate random UUIDs and use a faster (but still sufficiently random) RNG
uuid = { version = "1.8.0", features = ["v4" , "fast-rng"] }

[target.'cfg(unix)'.dependencies]
termion = "3.0.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[build-dependencies]
cc = "1.0.94"

[lints]
workspace = true
