[package]
name = "hurl"
version = "3.0.0-SNAPSHOT"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Hurl, run and test HTTP requests"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"
rust-version = "1.69"

[lib]
name = "hurl"

[features]
# Treat warnings as a build error.
strict = []

[dependencies]
atty = "0.2.14"
base64 = "0.21.0"
brotli = "3.3.4"
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
clap = { version = "4.2.5", features = ["cargo", "string", "wrap_help"] }
colored = "2.0.0"
curl = "0.4.44"
curl-sys = "0.4.61"
encoding = "0.2.33"
float-cmp = "0.9.0"
glob = "0.3.1"
hex = "0.4.3"
hex-literal = "0.4.1"
hurl_core = { version = "3.0.0-SNAPSHOT", path = "../hurl_core" }
indexmap = "1.9.3"
libflate = "1.3.0"
libxml = "0.3.2"
md5 = "0.7.0"
percent-encoding = "2.2.0"
regex = "1.8.1"
serde = "1.0.160"
serde_json = "1.0.96"
sha2 = "0.10.6"
url = "2.3.1"
xmltree = { version = "0.10.3",  features = ["attribute-order"] }
lazy_static = "1.4.0"
# uuid features: lets you generate random UUIDs and use a faster (but still sufficiently random) RNG
uuid = { version = "1.3.1", features = ["v4" , "fast-rng"] }

[target.'cfg(unix)'.dependencies]
termion = "2.0.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[build-dependencies]
cc = "1.0.79"

