[package]
name = "hurl"
version = "1.6.0-snapshot"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Hurl, run and test HTTP requests"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"

[lib]
name = "hurl"

[features]
# Treat warnings as a build error.
strict = []

[dependencies]
atty = "0.2.14"
base64 = "0.13.0"
brotli = "3.3.2"
chrono = "0.4.19"
clap = "2.34.0"
colored = "2.0.0"
curl = "0.4.41"
encoding = "0.2.33"
float-cmp = "0.9.0"
glob = "0.3.0"
hex = "0.4.3"
hex-literal = "0.3.4"
hurl_core = { version = "1.6.0-snapshot", path = "../hurl_core" }
libflate = "1.1.1"
libxml = "0.3.0"
md5 = "0.7.0"
percent-encoding = "2.1.0"
regex = "1.5.4"
serde = "1.0.131"
serde_json = "1.0.72"
sha2 = "0.10.0"
url = "2.2.2"


[target.'cfg(unix)'.dependencies]
termion = "1.5.6"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[build-dependencies]
cc = "1.0.72"

