name: check
on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Prerequisites
      run: bin/check/install_prerequisites.sh
    - name: Rustfmt
      run: bin/check/rustfmt.sh
    - name: Clippy
      run: bin/check/clippy.sh
    - name: Shellcheck
      run: bin/check/shellcheck.sh
    - name: Black
      run: bin/check/black.sh
    - name: Check XML/HTML files
      run: bin/check/xmllint.sh
    - name: Run crates update
      run: bin/check/crates.sh 
    - name: Check CHANGELOG
      run: bin/check/changelog.sh 
    - name: Check ad hoc
      run: bin/check/ad_hoc.sh
